### PR TITLE
SIG-17562: Validate/test new GoSnowflake master HEAD after force-reset

### PR DESCRIPTION
**Pull request by agam**
### Description
A no-op commit to run CI after the recent force-reset for `master`

### Checklist
- [x] Code compiles correctly
- [ ] Run ``make fmt`` to fix inconsistent formats
- [x] Run ``make lint`` to get lint errors and fix all of them
- [x] Created tests which fail without the change (if possible)
- [ ] All tests passing
- [x] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by agam** [comment]
Test failures indicate some secrets are missing, looking.

**Comment by GregOwen** [comment]
Do you know why we lost those README changes? Is it possible we lost any other important changes?

**Comment by agam** [comment]
> Do you know why we lost those README changes? Is it possible we lost any other important changes?

Missed during merge-conflict resolution.

I was paranoid about what else might be different, so here's what I did:

1. Created a list of _all files that show a change_ between `master` and `4f7755158355ca934121f6f990ed2b4edc286eea` (the point before the upstream-merge, which I used as a baseline for _this_ sync with upstream)
2. Created another list of _all files that show a change_ between `4ef5ec2722bb6b1bbdbff89fc45fe560cd0f2887` (the master-head _before_ the force-reset) and `4f7755158355ca934121f6f990ed2b4edc286eea`

At this point, (1) represented everything that changed between a certain point in our (previous) history and upstream, and (2) represented everything that  changed between that same point in our history and our previous top-of-branch.

I took the _intersection_ of this list and validated changes to each file.

Most of the changes turned out to be copyright comment changes in upstream, but some additional changes did show up.

In the end, there were **two** commits in our history that needed to be re-created here: `9f3215c5478af5bc8fc448a6da95efc69b29af3f` and `5006ac7da1fb5e493deb442801d62e9cd04e9a89`.

(The changes to `README.rst` and (the part that was breaking CI) to `build-test.yml` came from the first of these two)

**Review by GregOwen — APPROVED** [review]

**Comment by agam** [comment]
More of the mechanical details, for future reference:

```
(at current HEAD)
git diff --name-only 4f7755158355ca934121f6f990ed2b4edc286eea | rg -v '^vendor' > ~/tmp/total-diff.txt

git checkout 4ef5ec2722bb6b1bbdbff89fc45fe560cd0f2887
git diff --name-only 4f7755158355ca934121f6f990ed2b4edc286eea | rg -v '^vendor' > ~/tmp/our-diff.txt
```

Then
```
comm -12 ~/tmp/our-diff.txt ~/tmp/total-diff.txt

.github/workflows/build-test.yml
async_test.go
auth.go
auth_test.go
bind_uploader.go
bindings_test.go
chunk_arrow.go
chunk_downloader.go
chunk_test.go
connection.go
connection_test.go
connection_util.go
converter.go
converter_test.go
ctx_test.go
datatype.go
datatype_test.go
doc.go
driver.go
driver_test.go
dsn.go
dsn_test.go
encrypt_util.go
encrypt_util_test.go
env_flags.go
errors.go
file_transfer_agent.go
file_util.go
go.mod
go.sum
local_util.go
monitoring.go
multistatement_test.go
ocsp.go
ocsp_test.go
old_driver_test.go
priv_key_test.go
put_get_test.go
put_get_user_stage_test.go
put_get_with_aws_test.go
put_get_with_azure_test.go
put_get_with_gcp_test.go
query.go
restful.go
restful_test.go
result.go
retry.go
rows.go
rows_test.go
secret_detector.go
secret_detector_test.go
statement_test.go
storage_client.go
telemetry.go
telemetry_test.go
util.go
version.go
```

**Comment by agam** [comment]
Turns out I missed `4f7755158355ca934121f6f990ed2b4edc286eea` while resolving `converter.go`, will cherry-pick that now.

**Pull request merged**
