### PR TITLE
SIG-20421: Update master with upstream 050222

### PR DESCRIPTION
**Pull request by agam**
### Description
- Updated to `upstream` @ `d34ce5fe3a421fc2a2d9283b703ad670bbc2a0e5`
- Client version is now: `1.6.9`
- Perf report: https://staging.sigmacomputing.io/sigma-on-sigma/workbook/Snowflake-Go-Driver-Updates-Hm0VmWLJZbgi9m4hWayjK/edit?:nodeId=HQ2HRBUB88
- Note: shows speedup !

### Checklist
- [x] Code compiles correctly
- [x] Run ``make fmt`` to fix inconsistent formats
- [x] Run ``make lint`` to get lint errors and fix all of them
- [x] Created tests which fail without the change (if possible)
- [x] All tests passing
- [ ] Extended the README / documentation, if necessary

### CODE REVIEW

**Comment by agam** [comment]
`git log --pretty=format:"%h%x09%an%x09%s"  upstream/master..HEAD`

```
491995d Agam Brahma     Merge branch 'master' into reset-to-upstream
351cd19 Agam Brahma     Log row-counts and byte-sizes for Snowflake results (#66)
1bcaaf7 Agam Brahma     Disable go 1.1.6 from build/test workflow (#65)
3732448 Mihai Claudiu Toader    SIG-18794: Fix a bug when looping to complete an async query (#60)
2d7e6ad Mihai Claudiu Toader    SIG-18794: Make getAsync wait until the query completes or times out. (#59)
48707af Mihai Claudiu Toader    SIG-18794: Fix handling of results response for canceled queries (#58)
1b93125 Mihai Claudiu Toader    SIG-18794: Refactor the monitoring fetcher & auto-cancel async (#57)
3103606 Mihai Claudiu Toader    SIG-18794: Fix getAsync() to not panic on context exceeded + test. (#56)
bf77a7e Agam Brahma     SIG-17456: additional logging to narrow down cause of invalid string-array coercion (#54)
f0095c0 Agam Brahma     SIG-18378: Gosnowflake rebase from upstream -- Feb 2022  (#53)
e039093 Yifeng-Sigma    not use qid from SFconnection when fetch monitoring data (#52)
fbf3cf3 Greg Owen       Allow clients to specify DataTypeNull explicitly (#50)
c0bedfa Yifeng-Sigma    add MonitoringResultFetcher to fetch monitoring (#48)
462e262 Agam Brahma     SIG-17456: Trap chunk-downloader errors with Sentry at Multiplex. (#44)
10295c0 Agam Brahma     Fix CI for current master (#47)
d9a154a Max Seiden      fix var inits (#46)
41c90a0 Max Seiden      add a cache to the FetchResult codepath to avoid API calls (#45)
a332f2c Agam Brahma     SIG-16907: Error out early when invalid state for multi-statement requests. (#43)
096793c Agam Brahma     Fix arrowToValue handling of timestamp_ltz at non-nanosecond scales (#24) (#42)
ede8c16 Agam Brahma     connection: export buildRowsForRunningQuery as FetchResult (#23) (#41)
c9843e6 Agam Brahma     SIG-17562: Update go.mod and upstream version dependency (#40)
691baab Agam Brahma     SIG-17562: Validate/test new GoSnowflake master HEAD after force-reset (#39)
413774a Agam Brahma     nit: compile errors and lint fixes
581e26a Agam Brahma     SIG-16907: Adding debug-logging to narrow down cause of nil exception. (#37)
ef8f488 Agam Brahma     Add more ways to get _some_ logging for failed requests (#36)
972625e Agam Brahma     Dump env-vars that are read in for a connection. (#35)
fa5e479 Agam Brahma     Create Env-var flags to control debug logging within adapter for retries (#34)
a9eafa3 Agam Brahma     More debugging around (1) retries and (2) query-monitoring (#33)
abfa4fa Agam Brahma     Misc debugging aids for retry-behavior. (#32)
0516eea Greg Owen       Allow client to specify clientTimeout in the DSN (#30)
a47aa4c Greg Owen       Allow client to specify any data type explicitly (#28)
702600d Greg Owen       Lint fix to get the automated tests running again (#29)
5ef7e29 Max Seiden      move monitoring to a goroutine; client decides how long it'll wait (#27)
afbfca4 Max Seiden      update interface
7e7501f Max Seiden      [monitoring] fetch the query graph for slow queries (#26)
0715091 Agam Brahma     Merge commit '4f7755158355ca934121f6f990ed2b4edc286eea' into agam/reset-to-upstream
4f77551 Luke Paulsen    Fix arrowToValue handling of timestamp_ltz at non-nanosecond scales (#24)
20ebcf6 James Gale      connection: export buildRowsForRunningQuery as FetchResult (#23)
bc49af6 Eric Bannatyne  Update README with steps for pulling changes from upstream (#22)
bdf9111 Eric Bannatyne  Update gosnowflake fork to latest upstream (#21)
5006ac7 Greg Owen       enable CI tests in our repo (#20)
a931f68 GregOwen        tell module that it's a fork
4013875 Max Seiden      add hook to fetch "monitoring" data
9f3215c Jack Qian       allow clients to set QUERY_TAG parameter via context
e6c0c66 GregOwen        Merge branch 'greg/old-origin' into greg/clean-reset-to-upstream-2021-05-25
4f5fe5f Jack Qian       Add get and set query tag helpers (#17)
be32754 Max Seiden      add hook to fetch "monitoring" data (#16)
fb12071 Greg Owen       Merge pull request #15 from sigmacomputing/greg/column-type-scale
2e4af09 GregOwen        ColumnType should include the scale
eeb5ada Joey Hain       [SIG-7631] backport upstream fix for gcp-hosted sf accounts (#14)
4b73908 Max Seiden      Add new DescribeContext helper (#12)
7ce7e6f James Gale      Merge pull request #11 from sigmacomputing/jlg/qid
588390a James Gale      expose QueryID value in Exec/Query results
e703782 Max Seiden      Fix Custom JSON Parser (#10)
9c08274 Max Seiden      respect ocsp flag (#9)
e21c5b2 Max Seiden      check err return from FuncGet (#8)
06ef13f Max Seiden      fix requestTimeout cfg bug; small fixes for handling request timeouts (#7)
1988c6e Max Seiden      make use of Context more consistent across functions and fn pointers (#6)
47dcac4 Max Seiden      fix chunk downloader error handling (#5)
9da2b32 Max Seiden      Merge pull request #4 from sigmacomputing/max/make_tests_work
c4e90f2 Max Seiden      make tests work
0322c1b Max Seiden      fixes and checking in secrets
a2fc8bf Max Seiden      Merge pull request #2 from mhseiden/max/retry_context
9a539ca Max Seiden      do not sleep through a context timeout
```

**Comment by agam** [comment]
`git log --pretty=format:"%h %as%x09%an%x09%s"  upstream/master -20`

```                                                                                                                                                                              
d34ce5f 2022-04-19      Kiran Dama      SNOW-577528: Bumped up GoLang connector PATCH version from 1.6.8 to 1.6.9 (#572) (#573)
a2e1e06 2022-04-13      sfc-gh-jbahk    SNOW-563221 Fix Missing Locale (#571)
33242ea 2022-04-13      SimbaGithub     Fixes SNOW-559224. The driver closes channel twice in async mode and throws error close of closed channel panic. (#568)
c58a5ed 2022-04-13      SimbaGithub     Drop support for go 1.16 and add support for go 1.18 (#569)
6535578 2022-03-15      Kiran Dama      SNOW-559412: Bumped up GoLang connector PATCH version from 1.6.7 to 1.6.8 (#560) (#561)
e24bda4 2022-02-23      sfc-gh-jbahk    SNOW-546088 Export UUID (#554)
e08419d 2022-02-22      sfc-gh-jbahk    SNOW-542628 Update Default Server Side Error (#553)
678701a 2022-02-16      Kiran Dama      SNOW-544029: Bumped up GoLang connector PATCH version from 1.6.6 to 1.6.7 (#548) (#549)
75ec2df 2022-02-15      Greg Owen       Allow Client to specify ClientTimeout in the DSN (#484)
903838d 2022-02-15      sfc-gh-jbahk    SNOW-526255 Fix Time Scale for Arrow (#547)
0ab4fdd 2022-02-15      yiksanchan      Fix Select 1 Bug (#511)
97c3d6f 2022-02-11      sfc-gh-jbahk    Formatting & Lint (#545)
1bd84af 2022-02-10      ddl-giuliocapolino      Arrow Record Result Batches (#544)
a85a42a 2022-02-09      sfc-gh-jbahk    SNOW-521578 PUT Memory Enhancements (#527)
6f78a2b 2022-02-01      sfc-gh-jbahk    SNOW-535399 Fix GetQueryStatus Bug (#539)
015903e 2022-01-31      sfc-gh-jbahk    SNOW-440362 Implement UUIDv4 (#541)
67c7cf2 2022-01-26      sfc-gh-jbahk    SNOW-534077 Multi-Statement Missing Result IDs (#534)
705a4a1 2022-01-19      Kiran Dama      SNOW-530866: Bumped up GoLang connector PATCH version from 1.6.5 to 1.6.6 (#529)
941a4eb 2022-01-19      sfc-gh-jbahk    Refactor & Lint (#525)
6ee2a74 2022-01-11      sfc-gh-jbahk    Additional Copyrights (#522)
```

**Comment by mtoader** [comment]
> IMO we can change how commits are ordered; the method of cherry-picking back each of our commits after rebasing upstream on our branch provides the best history, but is more time-consuming.
> 
> But even with that we would still have to resolve conflicts between our code and whatever we pull in.

That's the point. Our code (meaning our commit on top the baseline) is the one that needs to evolve and be adapted to the baseline, we should not change the baseline to adapt to our code. That make is unsustainable over long term.

If on each rebase we get a chance to decide how our patches should evolve enables us to adapt them to the baseline changes / maybe remove / maybe push them upstream / etc. 

I'm aware it's more work every time but it less work overall.

**Comment by agam** [comment]
btw, this (rebasing upstream on our branch) is how I started out last time; see https://github.com/sigmacomputing/gosnowflake/pull/51.

I switched away from it because it lost the "clear attribution to Snowflake in history".

**Comment by mtoader** [comment]
> btw, this (rebasing upstream on our branch) is how I started out last time; see #51.
> 
> I switched away from it because it lost the "clear attribution to Snowflake in history".

I know. But this should have been the way: https://die-antwort.eu/techblog/2016-08-git-tricks-for-maintaining-a-long-lived-fork/ (even if we keep our branch on something else that master)

**Comment by agam** [comment]
The biggest difference between our situation and the one in the blog post is that we don't have a fork which is "slightly different and with changes regularly shared with upstream" -- we have a large number of changes which are never committed to upstream.

As a result, the process there would mean cherry-picking _every_ single change we have _ever_ made, on top of the "underlying upstream that has been updated".

**Comment by mtoader** [comment]
> The biggest difference between our situation and the one in the blog post is that we don't have a fork which is "slightly different and with changes regularly shared with upstream" -- we have a large number of changes which are never committed to upstream.
> 
> As a result, the process there would mean cherry-picking _every_ single change we have _ever_ made, on top of the "underlying upstream that has been updated".
> 
> 

That is the exact point. I think we do want that actually.

**Comment by agam** [comment]
Closing in favor of re-visiting our branch structure (see https://docs.google.com/document/d/1ZOZauKqd6UKmcq1ZsjsbYGkp-tybB7wsmDr_zsyvwi8/edit#)

**Pull request closed without merging**
